### PR TITLE
Remove resource plugin handling of vault/filter.xml

### LINKED ISSUE #43: maven-content-package-plugin is not adding subPackages to the vault/filter.xml
Given a standard project creation from the `aem-project-archetype` using 
```
mvn archetype:generate  \
  -DarchetypeRepository=http://repo.adobe.com/nexus/content/groups/public/  \
  -DarchetypeGroupId=com.adobe.granite.archetypes  \
  -DarchetypeArtifactId=aem-project-archetype  \
  -DarchetypeVersion=10  \
  -DappsFolderName=hsbc  \
  -DartifactName="test"
```

After adding the `acs-aem-commons[content]`  subPackage (see [commit](https://github.com/cpilsworth/archetype-filter-bug/commit/d7e2c434aee4361505a03f1219105f8b5cbc66a7)),  I've found that whilst the package is embedding, it is not being installed.

The reason for this seems to be that the package is not being added to the `META-INF/vault/filter.xml` file.  Adding the subpackage zip manually to this file allows it to be deployed as expected.

Normally the `content-package-maven-plugin` would generate this, but it seems as though the maven-resources-plugin [execution](https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/blob/master/src/main/archetype/ui.apps/pom.xml#L91) is replacing the filter.xml with the source original.  A respository containing the code exhibiting the issue can be found [here](https://github.com/cpilsworth/archetype-filter-bug).

### PR DESCRIPTION
**Pull request by cpilsworth**
NOTE: Created to fix some issues with the closed #43 PR.

Given a standard project creation from the aem-project-archetype using
```
mvn archetype:generate  \
  -DarchetypeRepository=http://repo.adobe.com/nexus/content/groups/public/  \
  -DarchetypeGroupId=com.adobe.granite.archetypes  \
  -DarchetypeArtifactId=aem-project-archetype  \
  -DarchetypeVersion=10
```
After adding the `acs-aem-commons-content` subPackage, I've found that whilst the package is embedding, it is not being installed.

The reason for this seems to be that the package is not being added to the `META-INF/vault/filter.xml` file.  Adding the subpackage zip manually to this file allows it to be deployed as expected.

Normally the `content-package-maven-plugin` would generate this, but it seems as though the `maven-resources-plugin` execution is replacing the `filter.xml` with the source original. A respository containing the code exhibiting the issue can be found [here](https://github.com/cpilsworth/archetype-filter-bug).

This PR removes the `maven-resources-plugin` handling of the `META-INF/vault` folder that is overwriting the filter.xml that the `content-package-maven-plugin` is updating with details of subPackages.

### CODE REVIEW

**Comment by cpilsworth** [comment]
@HitmanInWis hope this is clearer

**Comment by HitmanInWis** [comment]
Very much in favor of this, as I wasted a couple hours tracking this issue down myself so that I knew enough what to put into Google to find this fix.

**Comment by gopikrishna123** [comment]
I am getting the below error, Can you please help me to fix the error... Thanks in advance

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] company
[INFO] Company - Core
[INFO] Company - UI apps
[INFO] Company - UI content
[INFO] Company - Integration Tests Bundles
[INFO] Company - Integration Tests Launcher
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building company 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ company ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-maven) @ company ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ company ---
[INFO] Installing C:\symphony\company\pom.xml to C:\Users\kriss\.m2\repository\org\training\company\0.0.1-SNAPSHOT\company-0.0.1-SNAPSHOT.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Company - Core 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ company.core ---
[INFO] Deleting C:\symphony\company\core\target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-maven) @ company.core ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ company.core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\symphony\company\core\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ company.core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to C:\symphony\company\core\target\classes
[INFO] 
[INFO] --- maven-scr-plugin:1.20.0:scr (generate-scr-scrdescriptor) @ company.core ---
[INFO] Generating 1 MetaType Descriptors in C:\symphony\company\core\target\classes\OSGI-INF\metatype\org.training.company.core.schedulers.SimpleScheduledTask.xml
[INFO] Writing 1 Service Component Descriptors to C:\symphony\company\core\target\classes\OSGI-INF\org.training.company.core.filters.LoggingFilter.xml
[INFO] Writing 1 Service Component Descriptors to C:\symphony\company\core\target\classes\OSGI-INF\org.training.company.core.listeners.SimpleResourceListener.xml
[INFO] Writing 1 Service Component Descriptors to C:\symphony\company\core\target\classes\OSGI-INF\org.training.company.core.schedulers.SimpleScheduledTask.xml
[INFO] Writing 1 Service Component Descriptors to C:\symphony\company\core\target\classes\OSGI-INF\org.training.company.core.servlets.SimpleServlet.xml
[INFO] 
[INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ company.core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\symphony\company\core\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ company.core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to C:\symphony\company\core\target\test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ company.core ---
[INFO] Surefire report directory: C:\symphony\company\core\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.training.company.core.models.TestHelloWorldModel
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.332 sec - in org.training.company.core.models.TestHelloWorldModel

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-bundle-plugin:2.5.3:bundle (default-bundle) @ company.core ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ company.core ---
[INFO] Installing C:\symphony\company\core\target\company.core-0.0.1-SNAPSHOT.jar to C:\Users\kriss\.m2\repository\org\training\company.core\0.0.1-SNAPSHOT\company.core-0.0.1-SNAPSHOT.jar
[INFO] Installing C:\symphony\company\core\pom.xml to C:\Users\kriss\.m2\repository\org\training\company.core\0.0.1-SNAPSHOT\company.core-0.0.1-SNAPSHOT.pom
[INFO] 
[INFO] --- maven-bundle-plugin:2.5.3:install (default-install) @ company.core ---
[INFO] Installing org/training/company.core/0.0.1-SNAPSHOT/company.core-0.0.1-SNAPSHOT.jar
[INFO] Writing OBR metadata
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Company - UI apps 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ company.ui.apps ---
[INFO] Deleting C:\symphony\company\ui.apps\target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-maven) @ company.ui.apps ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ company.ui.apps ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 60 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ company.ui.apps ---
[INFO] No sources to compile
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] company ........................................... SUCCESS [1.250s]
[INFO] Company - Core .................................... SUCCESS [5.312s]
[INFO] Company - UI apps ................................. FAILURE [1.251s]
[INFO] Company - UI content .............................. SKIPPED
[INFO] Company - Integration Tests Bundles ............... SKIPPED
[INFO] Company - Integration Tests Launcher .............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.643s
[INFO] Finished at: Wed Jan 04 02:26:58 EST 2017
[INFO] Final Memory: 27M/355M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.day.jcr.vault:content-package-maven-plugin:0.0.24:check-signature (default-check-signature) on project company.ui.apps: The plugin com.day.jcr.vault:content-package-maven-plugin:0.0.24 requires Maven version 3.1.0 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginIncompatibleException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :company.ui.apps

**Comment by cpilsworth** [comment]
What version of maven are you using, looks like your version is not recent enough
> The plugin com.day.jcr.vault:content-package-maven-plugin:0.0.24 requires Maven version 3.1.0

**Comment by gopikrishna123** [comment]
@cpilsworth   I am using the maven 3.3.9 version, If I install the 3.1.0 does this effect any other projects??

**Comment by rombert** [comment]
@cpilsworth - sorry for keeping this PR idle for so long

>  A respository containing the code exhibiting the issue can be found here.

I think there's a link missing there :-)

**Comment by cpilsworth** [comment]
Sorry about that, must have deleted the repo - I'll recreate.

**Comment by cpilsworth** [comment]
Recreated the [repository](https://github.com/cpilsworth/archetype-filter-bug) demonstrating the issue.
Here are the steps 
* [subPackage gets added](https://github.com/cpilsworth/archetype-filter-bug/commit/f930aa0c05d72bb7282dd5bc661e3dd46c3b1363)
* [Filter XML does not contain the subPackage](https://github.com/cpilsworth/archetype-filter-bug/commit/8748b9461fd6075f1eac512877faf80e5c4e899a)
* [Apply the patch to remove resource copying](https://github.com/cpilsworth/archetype-filter-bug/commit/bee79ea42d3cf958730d0610315ef0dad4b70f1d)
* [Filter XML contains the subPackage entry](https://github.com/cpilsworth/archetype-filter-bug/commit/9e820511befa92f2fb7e6fbcabe867ac799b7d06)

**Comment by rombert** [comment]
The behaviour looks like a bug to me, I've opened bug #74 to track it.

A couple of notes:

- now additional files from src/main/content/META-INF/vault are no longer included, so the default config.xml and settings.xml are use . This is fine for me, but I would remove those files from the project as well
- would it make sense to remove the special handling from the ui.content model as well?

**Comment by cpilsworth** [comment]
Thanks for reviewing - that makes sense.  I have removed the resource handling from the `ui.content` project also and the `config.xml` and `settings.xml` from both @rombert

**Comment by rombert** [comment]
Manually applied in 

* 80fbd27e753e153d86a5b719391f363f91664079
* 5c9bea0646f74ca716aa205655632a4851e50f79
* e7bfedd9f1d03b6901a82a8e079933a8d6e3a1ad


Thanks for the contribution!

**Pull request closed without merging**
